config/routes.rb
CastroTheatre::Application.routes.draw do

  resources :floors

  resources :rooms

  root 'movies#index'
  resources :movies
  

end

app/models/floor.rb
class Floor < ActiveRecord::Base
  has_many :rooms
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  # validates :title, uniqueness
  validates_uniqueness_of :title

  # has_and_belongs_to_many :rooms
  # accepts_nested_attributes_for :rooms

  has_many :movie_rooms 
  has_many :rooms, through: :movie_rooms
  
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :floor
  # has_and_belongs_to_many :movies
  has_many :movie_rooms
  has_many :movies, through: :movie_rooms

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/floors_controller.rb
class FloorsController < ApplicationController
  before_action :set_floor, only: [:show, :edit, :update, :destroy]

  # GET /floors
  # GET /floors.json
  def index
    @floors = Floor.all
  end

  # GET /floors/1
  # GET /floors/1.json
  def show
  end

  # GET /floors/new
  def new
    @floor = Floor.new
  end

  # GET /floors/1/edit
  def edit
  end

  # POST /floors
  # POST /floors.json
  def create
    @floor = Floor.new(floor_params)

    respond_to do |format|
      if @floor.save
        format.html { redirect_to @floor, notice: 'Floor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @floor }
      else
        format.html { render action: 'new' }
        format.json { render json: @floor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /floors/1
  # PATCH/PUT /floors/1.json
  def update
    respond_to do |format|
      if @floor.update(floor_params)
        format.html { redirect_to @floor, notice: 'Floor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @floor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /floors/1
  # DELETE /floors/1.json
  def destroy
    @floor.destroy
    respond_to do |format|
      format.html { redirect_to floors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_floor
      @floor = Floor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def floor_params
      params.require(:floor).permit(:level, room_ids: [])
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_filter :set_movie, only: [:show, :edit, :update, :destroy]

  def index
    @movies = Movie.all
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to @movie, notice: 'Movie was successfully created.'
    else
      render action: 'new'
    end
  end  

  def edit
    @selection_rooms = Room.limit(3)
  end

  def update
    if @movie.update(movie_params)
      redirect_to @movie, notice: 'Movie was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_url
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id]) 
    end

    def movie_params
      params.require(:movie).permit(:title, :description, :duration, :room_ids => [])
    end



end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render action: 'show', status: :created, location: @room }
      else
        format.html { render action: 'new' }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/floors_helper.rb
module FloorsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/floors/_form.html.erb
<%= simple_form_for(@floor) do |f| %>
  <% if @floor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@floor.errors.count, "error") %> prohibited this floor from being saved:</h2>

      <ul>
      <% @floor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :level %> 
  <%= f.association :rooms %> 

 <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/floors/edit.html.erb
<h1>Editing floor</h1>

<%= render 'form' %>

<%= link_to 'Show', @floor %> |
<%= link_to 'Back', floors_path %>

app/views/floors/index.html.erb
<h1>Listing floors</h1>

<table>
  <thead>
    <tr>
      <th>Level</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @floors.each do |floor| %>
      <tr>
        <td><%= floor.level %></td>
        <td><%= link_to 'Show', floor %></td>
        <td><%= link_to 'Edit', edit_floor_path(floor) %></td>
        <td><%= link_to 'Destroy', floor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Floor', new_floor_path %>

app/views/floors/new.html.erb
<h1>New floor</h1>

<%= render 'form' %>

<%= link_to 'Back', floors_path %>

app/views/floors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Level:</strong>
  <%= @floor.level %>
</p>


<% if @floor.rooms.count > 0 %>
  <h5>Rooms</h5>
  <ul>
    <% @floor.rooms.each do |room| %>
      <li><%= link_to room.name, room_path(room) %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Edit', edit_floor_path(@floor) %> |
<%= link_to 'Back', floors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CastroTheatre</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Castro Theatre</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Browse Movies", movies_path %></li>
            <li><%= link_to "Browse Rooms", rooms_path %></li>
            <li><%= link_to "Browse Floors", floors_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span9"><%= yield %></div>
      <div class="span3">
        <h2>Castro Theatre</h2>
        The Castro Theatre was built in 1922 by pioneer San Francisco theatre entrepreneurs, the Nasser brothers, who started with a nickelodeon in 1908 in the Castro neighborhood.
        <br><br>
    The Castro was built at a cost of $300,000. The Castro's designer was Timothy L. Pflueger (1894-1946) who went on to become a famous Bay Area architect. In 1977, the Castro was designated City of San Francisco registered landmark number 100. It is one of the few remaining movie palaces in the nation from the 1920s that is still in operation.
      </div>
    </div>
  </div>
</body>
</html>

app/views/movies/_form.html.erb
<p>We already have a movie called Inception, please stop adding it.</p>

<%= simple_form_for @movie do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :duration %>

  <%= f.association :rooms, collection: @selection_rooms %>


  <p><%= f.submit %></p>
<% end %>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>
<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Movies</h1>
<ul>
  <% @movies.each do |movie| %>
    <li>
      <%= render partial: 'movie', locals: {movie: movie} %>
    </li>
  <% end %>
</ul>

app/views/movies/new.html.erb
<h1>Create Movie</h1>
<%= render 'form' %>

app/views/movies/show.html.erb
<%= render partial: 'movie', locals: {movie: @movie} %>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1>Listing rooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.number %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @room.number %>
</p>


<% if @room.floor %>
  <h5>Floor</h5>
  <p><%= @room.floor.level %></p>
<% end %> 



<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>